import type { Metadata } from "next";
import "./globals.css";
import "./fonts.css";
import Header from "@/components/UI/Header";

export const metadata: Metadata = {
  title: "Pinterest Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
